### ISSUE TITLE
undefined method `groups' for Chef::Resource::UserAccount

### ISSUE THREAD

**Issue by jcderose** [fnichol/chef-user#100]
This MAY be related to issue #95 . If so, I'll close this as a duplicate. 

My cookbook setup is as follows: 

- (custom) cookbook ap-ops requires (custom) recipe ap-baseline::default
- (custom) cookbook ap-baseline uses the user_account LWRP and requires the cookbook user (this cookbook)

If I converge a test kitchen node for ap-ops, it claims `undefined method 'groups' for Chef::Resource::UserAccount`.
```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/ap-ops/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `groups' for Chef::Resource::UserAccount

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/config_ssh.rb:34:in `block (2 levels) in from_file'
         /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/config_ssh.rb:30:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/config_ssh.rb:27:in `each'
         /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/config_ssh.rb:27:in `from_file'
         /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/default.rb:26:in `from_file'
         /tmp/kitchen/cache/cookbooks/ap-ops/recipes/default.rb:7:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/ap-baseline/recipes/config_ssh.rb:

        27:  node['allowed_users'].each do |uname|
        28:    @@ssh_key = Vault.logical.read("secret/eng/#{uname}").data[:ssh_key]
        29:
        30:    user_account uname do
        31:      action :create
        32:      home "/home/#{uname}"
        33:      shell '/bin/bash'
        34>>     groups ['sysadmin']
        35:      ssh_keygen false
        36:      ssh_keys @@ssh_key
        37:    end
        38:
        39:    @@all_keys << @@ssh_key
        40:  end
        41:
        42:  user_account 'anyperk' do
        43:    action :modify


       Running handlers:

       Running handlers complete


       Chef Client failed. 0 resources updated in 2.938709548 seconds
       [2015-11-11T11:07:17-08:00] ERROR: undefined method `groups' for Chef::Resource::UserAccount
       [2015-11-11T11:07:17-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

However, if I explicitly include the user cookbook in the ap-ops cookbook (via Berkshelf and the metadata.rb file), the converge finishes successfully. Is this by design? I was under the impression I only need to include the user cookbook dependency where the LWRP is used (in the ap-baseline cookbook).

**Comment by ohlol** [comment]
Where did you get the cookbook from? The one on supermarket is not updated. I tweeted @fnichol about it but have yet to hear anything.

**Comment by jcderose** [comment]
@ohlol I'm pulling the cookbook from the github repo.

```
source 'https://supermarket.chef.io'

metadata

cookbook 'ap-baseline', git: 'path/to/cookbook'
cookbook 'user', github: 'fnichol/chef-user'
```

**Comment by umangd-qubole** [comment]
facing same issue. I installed user cookbook via knife. Version is 0.4.2, same as in this repository.
@jcderose how did you get it working?

**Comment by jcderose** [comment]
@umangd1 I couldn't tell you why this works, but I moved all my cookbook version dependency statements from my `Berksfile` into `metadata.rb` in the (custom) wrapper cookbook calling the `user` cookbook. So previously it looked like:

```
# my-cookbook/Berksfile

source 'https://supermarket.chef.io'

metadata

cookbook 'user', github: 'fnichol/chef-user'
cookbook 'some_cookbook1', '= 1.8.6'		
cookbook 'some_cookbook2', '= 0.9.1'		
cookbook 'some_cookbook3', '= 1.1.2'
```
```
# my-cookbook/metadata.rb

...

depends 'user'
depends 'some_cookbook1'
depends 'some_cookbook2'
depends 'some_cookbook3'
```

And now it looks like:
```
# my-cookbook/Berksfile

source 'https://supermarket.chef.io'

metadata

cookbook 'user', github: 'fnichol/chef-user'
```
```
# my-cookbook/metadata.rb

...

depends 'user'
depends 'some_cookbook1', '= 1.8.6'	
depends 'some_cookbook2', '= 0.9.1'
depends 'some_cookbook3', '= 1.1.2'
```

**Comment by umangd1** [comment]
this is weird. I have a simple example with no other dependency. As @ohlol pointed out, the supermarket version is not the latest. I installed the latest version using knife-github-cookbooks gem and not facing this error anymore.

**Comment by theckman** [comment]
I just ran in to this issue as well. I'm downloading `0.4.2` from the Chef supermarket and it does not contain the a provider with the `groups` resource.

**Comment by nozpheratu** [comment]
Seems `groups` isn't available even from the Github source.... I can see it there in the source code, but the file that Berks pulls in doesn't have it, even if I explicitly set the source to the git repo.

**Comment by theckman** [comment]
It is available in the GitHub source. I think you need to explicitly provide the commit ref:

```
cookbook 'user', git: 'https://github.com/fnichol/chef-user.git', ref: 'fd2094cc8a'
```

**Comment by nozpheratu** [comment]
@theckman I found my issue, it was with Berkshelf's retarded dependency resolver. If you require cookbook "a" that uses a git as a source in cookbook "b", Berkshelf will default to using the version available on supermarket for cookbook "b" so long as the version matches rather than the Github source......

So basically I have to specify
```ruby
cookbook 'user', git: 'https://github.com/fnichol/chef-user.git
```

In both cookbook's Berkfiles...

**Comment by theckman** [comment]
@nozpheratu Ah, yeah. I hadn't even considered that. I usually keep my user stuff confined to a single cookbook, so I've only ever needed to hit one spot. :+1:

**Comment by nozpheratu** [comment]
@theckman This issue extends to other cookbooks that are fetched from git sources as well. The only reason I figured it out so soon after posting that is because I literally ran into the same problem an hour ago with another cookbook. :disappointed:

**Comment by nozpheratu** [comment]
Completely unrelated to the issue, but I shouldn't call their dependency solver retarded. After looking into the code it looks like it relies on semantic versioning to operate correctly, so the issue is more a lack of proper version control (which you can't really expect when pulling directly from a Github repo I suppose).
