### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by patcon** [fnichol/chef-user#101]
Seems there are some outstanding issues that could do with a release:
https://github.com/fnichol/chef-user/issues/82

Please and thanks! :)

**Comment by mrjcleaver** [comment]
+1 !

**Comment by timor-raiman** [comment]
+1 specifically the groups attribute - #95, #96

**Comment by mikemoate** [comment]
We'd also like to get the groups attribute changes released. I also note the latest version available in the chef supermarket is 0.4.2, but the last tagged release in this repo is 0.3.0.

@ranjib (as the last active contributor) is there anything I can do to help get a release out?

**Comment by c240amg** [comment]
+1

**Comment by g3kk0** [comment]
+1

**Comment by JJClements** [comment]
+1

**Comment by mikemoate** [comment]
@fnichol is this repo dead?

**Comment by legal90** [comment]
ping @ranjib

**Comment by davidkovaccs** [comment]
+1

**Comment by theckman** [comment]
Thanks to help from @fnichol and @ranjib I've just been added as a collaborator. I'll be working to cut `v0.5.0` from master either today or this weekend.

**Comment by theckman** [comment]
Ohai Chefs!

I'm happy to announce that `v0.5.0` has been released on to the Supermarket! Here is the release on GitHub listing the changes since the release of `0.4.2` in 2015:

* https://github.com/fnichol/chef-user/releases/tag/v0.5.0

This includes some bugfixes and feature additions.
