### ISSUE TITLE
Any way to set password expiry options?

### ISSUE THREAD

**Issue by JJClements** [fnichol/chef-user#115]
Is there any way using this cookbook to set password expiry options?

Typically:
`root@someserver:~# chage -l root`
`Last password change: Mar 24, 2017`
`Password expires: never`
`Password inactive: never`
`Account expires: never`
`Minimum number of days between password change: 0`
`Maximum number of days between password change: 99999`
`Number of days of warning before password expires: 7`

**Comment by theckman** [comment]
Thank you for opening this issue. That's a good question!

This cookbook is a wrapper around the `user` resource provided in the core of Chef. So we're only able to offer the functionality it offers as of right now. Doing some research, I don't believe there is a way to have the core `user` resource do password expiry:

- https://stackoverflow.com/questions/38320035/setting-password-expiry-using-chef-user-resource

I've not personally had to implement this within Chef, so I'm not sure I can offer a good workaround / solution. If you do come up with a solution that may work within this cookbook, I'd be more than happy to review a pull request to add the functionality.
