### ISSUE TITLE
created user is not sourcing /etc/profile.d/*

### ISSUE THREAD

**Issue by darthdeus** [fnichol/chef-user#27]
I have created a user in vagrant image, simply as

```
user_account "deploy" do
  comment   "deployer"
  ssh_keys  ["3dc348d9af8027df7b9c...", "2154d3734d609eb5c452..."]
  home      "/home/deploy"
  shell     "/bin/bash"
end
```

but the problem is that when I do `sudo su deploy`, he doesn't source scripts from `/etc/profile.d/*`, even though he has the rights to do it, and the `vagrant` user does it by default.

Is there something else that I need to do? I'm doing this on ubuntu 10.04

**Comment by toontong** [comment]
2012年到现在还不修复这个问题, 搞毛阿, 都2015年了

**Comment by theckman** [comment]
@darthdeus I've just recently stared to help out with this cookbook. Sorry it's taken nearly 4 years to get you a reply.

I think this has less to do with this cookbook and more about the type of shell that's being invoked by `sudo su`. I believe `/etc/profile` and `/etc/profile.d` are only sourced for login shells. When you invoke `sudo su <user>` you don't get a login shell. I believe if you were to switch to the user by running `sudo -iu <user>` you would have `/etc/profile.d/*` be sourced.

I've confirmed this in a test-kitchen VM that was generated by the integration tests of this repo. You can also determine which kind of shell you're in by running `echo $0`. If the shell name starts with a `-`, it's a login shell.

I don't believe this is a `chef-user` issue and will close this issue. If you think this isn't the case, please give me a shout and I'd be happy to reopen the ticket.
