### ISSUE TITLE
Please release 0.4.0 of this cookbook.

### ISSUE THREAD

**Issue by poliva83** [fnichol/chef-user#71]
Its been over 2 years since 0.3.0 was released but there many fixes made to master HEAD in that time (last change April 29th, 2014). Can you please release the next version of this cookbook? Suggest it should be version 0.4.0 (or maybe even 1.0.0).

**Comment by WouterSioen** [comment]
:+1: Any news on this one?

**Comment by drywheat** [comment]
:+1:

**Comment by ranjib** [comment]
done. thanks for being patient :0-) . and sorry for the delay

**Comment by rberger** [comment]
Yay! Thank you!

**Comment by poliva83** [comment]
:+1:
