### ISSUE TITLE
Can't modify users

### ISSUE THREAD

**Issue by daften** [fnichol/chef-user#74]
The error message is:
STDERR: usermod: user jenkins is currently logged in

I only need to add private keys to the user. Is it possible to protect so the user resource so that would be possible?

**Comment by nkadel-skyhook** [comment]
This normally only happens when the user's uid, gid, homedirectory, shell, comments, etc. are being altered. Have you verified that nothing else  is being changed?

**Comment by daften** [comment]
Sorry, it seems a lot of old issues were buried. In the meantime, I've been able to work around this, so closing this.
