### ISSUE TITLE
ERROR: Failed to load data bag item: "users" "deploy"

### ISSUE THREAD

**Issue by danhanly** [fnichol/chef-user#90]
So I built my cookbook using kitchen and it's passes all tests and the users are created.

If I pull my cookbook in as a Berkshelf dependency and launch a provision instruction via `vagrant up --provision`, I'm getting the following error:

`ERROR: Failed to load data bag item: "users" "deploy"`

Here is my deploy data bag (accessible via my-cookbook/data_bags/users/deploy.json):

``` json
{
  "id": "deploy",
  "comment": "Deploy User",
  "home": "/home/deploy",
  "groups": ["deploy"],
  "ssh_keys": ["ssh-rsa 12345 email@example.com", "ssh-rsa 12345 email@example.com"],
  "action": "create"
}
```

When building through vagrant, is there something specific I need to do to get this working?

**Comment by danhanly** [comment]
I've figured it out.

Essentially, I need to duplicate this data bag and include it within the root installation, then tell vagrant where the data bags are stored. It seems when cookbooks are pulled in via dependencies rather than as the root product, the data bags aren't being honoured.

In my Vagrantfile:

```ruby
config.vm.provision "chef_solo" do |chef|
    chef.data_bags_path = "chef/data"
end
```

In my directory structure:

```
| - chef
| -  - data
| -  -  -  users
| -  -  -  -  deploy.json
|_Vagrantfile
```

**Comment by theckman** [comment]
@danhanly In my experience, you do need to be explicit with these kinds of things. Things (as of recent) have started to get more and more automated.

This has been open for a bit of time with no update, so I'm going to close this issue. Please raise another if you need some help.
