### ISSUE TITLE
Missing "groups" attribute for user_account

### ISSUE THREAD

**Issue by ianbamforth** [fnichol/chef-user#95]
The documentation for user_account has `groups` listed (twice!), but it doesn't appear to work.  Looking in the resources/ folder, groups is the only attribute not listed.

**Comment by acqant** [comment]
+1

What needs to be done... I'll help out.

**Comment by acqant** [comment]
https://github.com/fnichol/chef-user/pull/96

**Comment by theckman** [comment]
A new release has been cut (`0.5.0`) which should address this issue. Sorry for the delay.
